### ISSUE TITLE
Captalys

### ISSUE THREAD

**Issue by lsevero** [renatoalencar/clojure-empregos-brasil#1]
Gostaria de adicionar a Captalys na lista.
Apesar de não ter nenhuma vaga específica para programadores Clojure é uma habilidade que estamos sempre procurando pois usamos muito.
A empresa aceita trabalho remoto e se localiza em São Paulo-SP

A lista completa de vagas de emprego pra captalys pode ser encontrada aqui: https://captalys.gupy.io/

**Comment by renatoalencar** [comment]
O quanto de Clojure vocês usam no dia a dia e com que frequência alguém novo que é contratado vai trabalhar com Clojure?

**Comment by lsevero** [comment]
Depende muito da API que temos que desenvolver ou dar manutenção, mas diria que hoje de 50~60% do nosso back-end é Clojure, a outra parte é python.

**Comment by renatoalencar** [comment]
Certo, eu notei que as vagas de back end e que são parte Clojure caem na mesma sessão que QA por exemplo, e que portanto não é possível filtrar quais vagas são Clojure ou não.

Sendo assim, no momento eu vou adicionar na lista de vagas adicionadas manualmente. Assim que for possível separar as vagas de Clojure das demais de forma automática, sinta-se livre para abrir uma issue ou um PR.

Vou subir um PR com a vaga e te adiciono como reviewer.
